In [1]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a1 = np.zeros([3, 3])
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a.shape

(5,)

In [2]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
c = np.empty(5)
c

array([0., 0., 0., 0., 0.])

In [ ]:
aa = np.linspace(2,10,5)  # from 2 to 10 , total 5 elements
aa

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
bb = np.array([5,5])
bb

array([5, 5])

In [ ]:
pyList = [1,2,3,4,5]
cc = np.array(pyList)  # python list to numpy array
cc

array([1, 2, 3, 4, 5])

In [7]:
multiArr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
multiArr[0, 1:6:2]  # arry first row , then index 1-6 with interval of 2

array([2, 4, 6])

In [8]:
#identiry matrix
idntyArr = np.identity(5)
idntyArr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr1 = np.array([[1,2,3,4,5]])
rptArr1 = np.repeat(arr1,3,axis=0)
rptArr2 = np.repeat(arr1,3,axis=1)
print(rptArr1)
print("-------")
print(rptArr2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
-------
[[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]]
