In [3]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [4]:
a1 = np.zeros([3, 3])
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a.shape

(5,)

In [ ]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
c = np.empty(5)
c

array([0., 0., 0., 0., 0.])

In [ ]:
aa = np.linspace(2,10,5)  # from 2 to 10 , total 5 elements
aa

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
bb = np.array([5,5])
bb

array([5, 5])

In [ ]:
pyList = [1,2,3,4,5]
cc = np.array(pyList)  # python list to numpy array
cc

array([1, 2, 3, 4, 5])