In [1]:
# pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 2.2 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [8]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b= np.array([1,2,3],dtype="int16")
b

array([1, 2, 3], dtype=int16)

In [13]:
c= np.array([1.00,2.00,3.00])
c

array([1., 2., 3.])

In [14]:
#get item size of array
a.itemsize

8

In [15]:
b.itemsize

2

In [16]:
c.itemsize

8

In [17]:
e= np.array([ [1,2,3],[4,5,6] ])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
e.itemsize

8

In [20]:
e.ndim

2

In [21]:
# how many items are there in the array
e.size

6

In [22]:
#total size of array in term of memory bytes
e.itemsize*e.size

48

In [23]:
#total size of array in term of memory bytes
e.nbytes

48

In [1]:
# 2 dimentional Array
# and the trics

In [4]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
a[1,3]

9

In [6]:
# or we can use negative notation
a[1,-2]

9

In [7]:
# get a specific row
a[1,:]

array([ 6,  7,  8,  9, 10])

In [8]:
# get a specific column
a[:,2]

array([3, 8])

In [10]:
# getting multiple value in step
# array[ rowindex, startindex : endindex+1  stepsize]

a[1:4:2]

array([[ 6,  7,  8,  9, 10]])

In [2]:
## fill up array
## all 0 array
a= np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [7]:
b=np.zeros([3,3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c= np.zeros([3,2,3])
c

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
## all 1 matrix
e= np.ones(3)
e

array([1., 1., 1.])

In [10]:
f= np.ones([2,3])
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
### full with custome value
## np.full( [x,y] , value)

g= np.full([3,3],99)
g

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])