In [1]:
# pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 2.2 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [12]:
b= np.array([1,2,3],dtype="int16")
b

array([1, 2, 3], dtype=int16)

In [13]:
c= np.array([1.00,2.00,3.00])
c

array([1., 2., 3.])

In [14]:
#get item size of array
a.itemsize

8

In [15]:
b.itemsize

2

In [16]:
c.itemsize

8

In [17]:
e= np.array([ [1,2,3],[4,5,6] ])
e

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
e.itemsize

8

In [20]:
e.ndim

2

In [21]:
# how many items are there in the array
e.size

6

In [22]:
#total size of array in term of memory bytes
e.itemsize*e.size

48

In [23]:
#total size of array in term of memory bytes
e.nbytes

48